sudo: required
services:
    - docker

before_install:
    - docker build -t elvisjorge/docker_activity -f Dockerfile.dev .

script:
    - dockker run elvisjorge/docker_activity npm run test -- --coverage