sudo: required
services:
    - docker

before_install:
    - docker build -t elvisjorge/docker_activity -f Dockerfile.dev .

script:
    - docker run elvisjorge/docker_activity npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app:  "docker_activity"
    env: "DockerActivity-env"
    bucket_name: "elasticbeanstalk-us-east-2-231271387299"
    bucket_path: "docker_activity"
    on:
        branch: master
